name: Reusable workflow example in top level repo

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - run: echo Parent User is ${{ inputs.username }}.
  composite_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - id: composite
        uses: ./ga-test-sub/composite
        with:
          who-to-greet: "Reusable workflow called me"
      - run: echo random-number ${{ steps.composite.outputs.random-number }}
        shell: bash
